name: cs_elements
description: A pub package
dependencies:
  cookies: any
  http: any
  polymer: any
  quiver: '>=0.18.0'
dev_dependencies:
  unittest: any
transformers:
- polymer:
    entry_points:
    - example/qrcode.html
    - test/route/route_test.html
    - test/context_panel/context_panel_test.html
